spring:
  application:
    name: assignment
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        search:
          backend:
            directory:
              type: local-heap
            type: lucene
  h2:
    console:
      enabled: true

recipe:
  api:
    url: https://dummyjson.com/recipes
